# A sample Gemfile
source 'http://rubygems.org'

gem 'rails'
gem 'haml-rails'
gem 'haml'
gem 'will_paginate'
gem 'pg'
gem 'devise'
gem 'cancan'
gem 'jquery-rails'
gem 'carrierwave'

gem 'web-app-theme'
gem 'hpricot'
gem 'capybara'
gem 'ruby_parser'
gem 'rack-raw-upload'
gem 'nokogiri'
gem 'itslog'
gem 'json'
gem 'numerizer'
gem 'chronic_duration'
gem 'geokit'
gem 'watu_table_builder', :require => 'table_builder'
gem 'yaml_db'
gem 'aws-s3'
gem 'thin'
gem 'fog'

