# A sample Gemfile
source 'http://rubygems.org'
ruby '2.1.0'
gem 'rails'
gem 'haml-rails'
gem 'haml'
gem 'will_paginate'
gem 'pg'
gem 'devise'
gem 'cancan'
gem 'jquery-rails'
gem 'carrierwave'
gem 'web-app-theme'
gem 'hpricot'
gem 'ruby_parser'
gem 'rack-raw-upload'
gem 'nokogiri'
gem 'itslog'
gem 'json'
gem 'numerizer'
gem 'chronic_duration'
gem 'geokit'
gem 'watu_table_builder', :require => 'table_builder'
gem 'yaml_db'
gem 'aws-s3'
gem 'thin'
gem 'fog'
gem 'fullcalendar-rails'
gem 'newrelic_rpm'
gem 'geocoder'
gem 'wunderground'
gem 'geokit-rails'
gem 'unf'
gem 'logging-rails', :require => 'logging/rails'


