#   cities => City.create([},{ :name   'Chicago', },{ :name   'Copenhagen'}

#  Mayor.create(:name   'Daley', :city   cities.first)

weather_translations=WeatherTranslations.create([
{:translation_id =>  200,:de =>  'Gewitter mit leichtem Regen'},
{:translation_id =>  201,:de =>  'Gewitter mit Regen'},
{:translation_id =>  202,:de =>  'Gewitter mit starkem Regen'},
{:translation_id =>  210,:de =>  'leichte Gewitter'}, 
{:translation_id =>  211,:de =>  'Gewitter'},
{:translation_id =>  212,:de =>  'schwere Gewitter'},
{:translation_id =>  221,:de =>  'einige Gewitter'},
{:translation_id =>  230,:de =>  'Gewitter mit leichtem Nieselregen'},
{:translation_id =>  231,:de =>  'Gewitter mit Nieselregen'},
{:translation_id =>  232,:de =>  'Gewitter mit starkem Nieselregen'},
{:translation_id =>  300,:de =>  'leichtes Nieseln'},
{:translation_id =>  301,:de =>  'Nieseln'},
{:translation_id =>  302,:de =>  'starkes Nieseln'},
{:translation_id =>  310,:de =>  'leichter Nieselregen'},
{:translation_id =>  311,:de =>  'Nieselregen'},
{:translation_id =>  312,:de =>  'starker Nieselregen'},
{:translation_id =>  321,:de =>  'Nieselschauer'},
{:translation_id =>  500,:de =>  'leichter Regen'},
{:translation_id =>  501,:de =>  'mäßiger Regen'},
{:translation_id =>  502,:de =>  'sehr starker Regen'},
{:translation_id =>  503,:de =>  'sehr starker Regen'},
{:translation_id =>  504,:de =>  'Starkregen'},
{:translation_id =>  511,:de =>  'Eisregen'},
{:translation_id =>  520,:de =>  'leichte Regenschauer'},
{:translation_id =>  521,:de =>  'Regenschauer'},
{:translation_id =>  522,:de =>  'heftige Regenschauer'},
{:translation_id =>  600,:de =>  'mäßiger Schnee'},
{:translation_id =>  601,:de =>  'Schnee'},
{:translation_id =>  602,:de =>  'heftiger Schneefall'},
{:translation_id =>  611,:de =>  'Graupel'},
{:translation_id =>  621,:de =>  'Schneeschauer'},
{:translation_id =>  701,:de =>  'trüb'},
{:translation_id =>  711,:de =>  'Rauch'},
{:translation_id =>  721,:de =>  'Dunst'},
{:translation_id =>  731,:de =>  'Sand / Staubsturm'},
{:translation_id =>  741,:de =>  'Nebel'},
{:translation_id =>  800,:de =>  'klarer Himmel'},
{:translation_id =>  801,:de =>  'ein paar Wolken'},
{:translation_id =>  802,:de =>  'überwiegend bewölkt'},
{:translation_id =>  803,:de =>  'überwiegend bewölkt'},
{:translation_id =>  804,:de =>  'wolkenbedeckt'},
{:translation_id =>  900,:de =>  'Tornado'},
{:translation_id =>  901,:de =>  'Tropensturm'},
{:translation_id =>  902,:de =>  'Hurrikan'},
{:translation_id =>  903,:de =>  'kalt'},
{:translation_id =>  904,:de =>  'heiß'},
{:translation_id =>  905,:de =>  'windig'},
{:translation_id =>  906,:de =>  'Hagel'},
{:translation_id =>  950,:de =>  'Setting'},
{:translation_id =>  951,:de =>  'Calm'},
{:translation_id =>  952,:de =>  'Light breeze'},
{:translation_id =>  953,:de =>  'Gentle Breeze'},
{:translation_id =>  954,:de =>  'Moderate breeze'},
{:translation_id =>  955,:de =>  'Fresh Breeze'},
{:translation_id =>  956,:de =>  'Strong breeze'},
{:translation_id =>  957,:de =>  'High wind near gale'},
{:translation_id =>  958,:de =>  'Gale'},
{:translation_id =>  959,:de =>  'Severe Gale'},
{:translation_id =>  960,:de =>  'Storm'},
{:translation_id =>  961,:de =>  'Violent Storm'},
{:translation_id =>  962,:de =>  'Hurricane'}])